import {
  Activity,
  Antenna,
  Atom,
  BatteryCharging,
  Bell,
  Bluetooth,
  Blocks,
  BookMarked,
  BookOpen,
  Bot,
  BotMessageSquare,
  Box,
  Boxes,
  Braces,
  Brain,
  Bug,
  Cable,
  ChartNoAxesCombined,
  CircuitBoard,
  ClipboardCheck,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudUpload,
  Code,
  CodeXml,
  Cog,
  Compass,
  Component,
  Cpu,
  Crown,
  Database,
  Dna,
  FileText,
  FlaskConical,
  GitBranch,
  GitFork,
  GitPullRequest,
  GraduationCap,
  Gauge,
  Hammer,
  HardDrive,
  Laptop,
  Library,
  Lightbulb,
  Mail,
  Map,
  MapPinned,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Microchip,
  Microscope,
  MonitorCog,
  Move3D,
  Navigation,
  Network,
  Nfc,
  NotebookPen,
  Orbit,
  PackageCheck,
  PanelsTopLeft,
  PencilRuler,
  Pickaxe,
  Plug,
  PlugZap,
  Radar,
  Radio,
  RadioTower,
  Rocket,
  Router,
  Rss,
  Satellite,
  SatelliteDish,
  ScanSearch,
  School,
  SearchCheck,
  Send,
  Server,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  TabletSmartphone,
  Target,
  Telescope,
  Terminal,
  Usb,
  Users,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type TagIconCandidate = {
  name: string;
  label: string;
  slug: string;
  color: string;
  Icon: LucideIcon;
};

export type TagIconGroup = {
  title: string;
  description: string;
  accent: string;
  items: TagIconCandidate[];
};

function icon(
  name: string,
  label: string,
  slug: string,
  color: string,
  Icon: LucideIcon,
): TagIconCandidate {
  return { name, label, slug, color, Icon };
}

export const TAG_ICON_GROUPS: TagIconGroup[] = [
  {
    title: "통신 / 네트워크",
    description: "무선, 라디오, 알림, 채널, 외부 연동 태그에 어울리는 후보",
    accent: "#2563eb",
    items: [
      icon("Antenna", "안테나", "antenna", "#2563eb", Antenna),
      icon("Radio", "무전", "radio", "#1d4ed8", Radio),
      icon("RadioTower", "기지국", "radio_tower", "#1e40af", RadioTower),
      icon("Wifi", "와이파이", "wifi", "#0284c7", Wifi),
      icon("Router", "라우터", "router", "#0369a1", Router),
      icon("Satellite", "위성", "satellite", "#0f766e", Satellite),
      icon("SatelliteDish", "위성 수신", "satellite_dish", "#0e7490", SatelliteDish),
      icon("Rss", "피드", "feed", "#ea580c", Rss),
      icon("Bluetooth", "블루투스", "bluetooth", "#2563eb", Bluetooth),
      icon("Nfc", "NFC", "nfc", "#0891b2", Nfc),
      icon("Network", "네트워크", "network", "#4338ca", Network),
      icon("Webhook", "웹훅", "webhook", "#7c3aed", Webhook),
      icon("Radar", "레이더", "radar", "#047857", Radar),
      icon("MessageSquare", "공지 채널", "channel", "#0f766e", MessageSquare),
      icon("MessagesSquare", "토론", "discussion", "#475569", MessagesSquare),
      icon("Send", "송신", "transmit", "#0369a1", Send),
      icon("Mail", "메일", "mail", "#334155", Mail),
      icon("Megaphone", "홍보", "promotion", "#be123c", Megaphone),
      icon("Bell", "알림", "notice", "#b45309", Bell),
    ],
  },
  {
    title: "IoT / 임베디드",
    description: "보드, 센서, 장비, 클라우드 연결 태그에 바로 쓰기 좋은 후보",
    accent: "#047857",
    items: [
      icon("Cpu", "CPU", "cpu", "#047857", Cpu),
      icon("Microchip", "마이크로칩", "microchip", "#065f46", Microchip),
      icon("CircuitBoard", "회로", "circuit", "#047857", CircuitBoard),
      icon("Cable", "케이블", "cable", "#475569", Cable),
      icon("Plug", "플러그", "plug", "#334155", Plug),
      icon("PlugZap", "전원", "power", "#ca8a04", PlugZap),
      icon("Usb", "USB", "usb", "#475569", Usb),
      icon("HardDrive", "스토리지", "storage", "#64748b", HardDrive),
      icon("Server", "서버", "server", "#475569", Server),
      icon("Database", "데이터", "database", "#0f766e", Database),
      icon("Cloud", "클라우드", "cloud", "#0284c7", Cloud),
      icon("CloudCog", "클라우드 제어", "cloud_ops", "#0369a1", CloudCog),
      icon("CloudUpload", "업로드", "upload", "#2563eb", CloudUpload),
      icon("CloudDownload", "다운로드", "download", "#1d4ed8", CloudDownload),
      icon("MonitorCog", "장비 설정", "device_config", "#334155", MonitorCog),
      icon("Laptop", "랩톱", "laptop", "#0f172a", Laptop),
      icon("TabletSmartphone", "모바일 장치", "mobile_device", "#475569", TabletSmartphone),
      icon("Smartphone", "스마트폰", "smartphone", "#334155", Smartphone),
      icon("BatteryCharging", "배터리", "battery", "#16a34a", BatteryCharging),
      icon("Zap", "전기", "electric", "#ca8a04", Zap),
    ],
  },
  {
    title: "로봇 / 제어",
    description: "로봇, 이동, 센싱, 제어, 자동화 팀 태그 후보",
    accent: "#0f172a",
    items: [
      icon("Bot", "로봇", "robot", "#111827", Bot),
      icon("BotMessageSquare", "로봇 안내", "robot_assist", "#1f2937", BotMessageSquare),
      icon("Cog", "기어", "mechanism", "#334155", Cog),
      icon("Settings", "제어 설정", "control", "#475569", Settings),
      icon("SlidersHorizontal", "튜닝", "tuning", "#475569", SlidersHorizontal),
      icon("Gauge", "계측", "measurement", "#0f766e", Gauge),
      icon("Activity", "동작 신호", "motion_signal", "#16a34a", Activity),
      icon("Compass", "방향", "heading", "#0369a1", Compass),
      icon("Map", "지도", "mapping", "#2563eb", Map),
      icon("MapPinned", "위치", "localization", "#1d4ed8", MapPinned),
      icon("Navigation", "주행", "navigation", "#0e7490", Navigation),
      icon("Move3D", "3D 이동", "move3d", "#7c3aed", Move3D),
      icon("Box", "물체", "object", "#92400e", Box),
      icon("Orbit", "궤도", "orbit", "#4338ca", Orbit),
      icon("Radar", "센싱", "sensing", "#047857", Radar),
      icon("Workflow", "자동화", "automation", "#0f766e", Workflow),
    ],
  },
  {
    title: "개발 / 소프트웨어",
    description: "코딩, 저장소, 버그 수정, 배포·시스템 개발 태그 후보",
    accent: "#7c3aed",
    items: [
      icon("Code", "코드", "code", "#4c1d95", Code),
      icon("CodeXml", "마크업", "markup", "#6d28d9", CodeXml),
      icon("Braces", "API", "api", "#7c3aed", Braces),
      icon("Terminal", "터미널", "terminal", "#111827", Terminal),
      icon("GitBranch", "브랜치", "git_branch", "#4338ca", GitBranch),
      icon("GitFork", "포크", "git_fork", "#4f46e5", GitFork),
      icon("GitPullRequest", "PR", "pull_request", "#2563eb", GitPullRequest),
      icon("Bug", "버그", "bugfix", "#dc2626", Bug),
      icon("Wrench", "수리", "fix", "#475569", Wrench),
      icon("Hammer", "빌드", "build", "#92400e", Hammer),
      icon("Rocket", "배포", "launch", "#db2777", Rocket),
      icon("PanelsTopLeft", "프론트엔드", "frontend", "#0891b2", PanelsTopLeft),
      icon("Blocks", "모듈", "module", "#0f766e", Blocks),
      icon("Component", "컴포넌트", "component", "#4338ca", Component),
      icon("PackageCheck", "릴리즈", "release", "#047857", PackageCheck),
      icon("ShieldCheck", "보안", "security", "#166534", ShieldCheck),
    ],
  },
  {
    title: "연구 / 실험",
    description: "랩, 논문, 데이터, 검증, 알고리즘 연구 태그 후보",
    accent: "#b45309",
    items: [
      icon("FlaskConical", "실험", "experiment", "#b45309", FlaskConical),
      icon("Microscope", "현미경", "microscope", "#92400e", Microscope),
      icon("Telescope", "관측", "telescope", "#7c2d12", Telescope),
      icon("Atom", "과학", "science", "#0e7490", Atom),
      icon("Dna", "바이오", "bio", "#16a34a", Dna),
      icon("Brain", "AI", "ai", "#7c3aed", Brain),
      icon("ScanSearch", "분석", "analysis", "#0369a1", ScanSearch),
      icon("SearchCheck", "검증", "verification", "#047857", SearchCheck),
      icon("Lightbulb", "아이디어", "idea", "#ca8a04", Lightbulb),
      icon("ChartNoAxesCombined", "리포트", "report", "#2563eb", ChartNoAxesCombined),
      icon("Activity", "신호 분석", "signal", "#16a34a", Activity),
      icon("ClipboardCheck", "실험 기록", "lab_note", "#475569", ClipboardCheck),
      icon("FileText", "논문", "paper", "#334155", FileText),
      icon("Database", "데이터셋", "dataset", "#0f766e", Database),
    ],
  },
  {
    title: "공부 / 교육",
    description: "스터디, 강의, 세미나, 멘토링, 학습 기록 태그 후보",
    accent: "#0e7490",
    items: [
      icon("BookOpen", "스터디", "study", "#0e7490", BookOpen),
      icon("BookMarked", "교재", "textbook", "#0369a1", BookMarked),
      icon("GraduationCap", "교육", "education", "#1d4ed8", GraduationCap),
      icon("NotebookPen", "필기", "note", "#334155", NotebookPen),
      icon("PencilRuler", "연습", "practice", "#475569", PencilRuler),
      icon("Library", "자료실", "library", "#92400e", Library),
      icon("School", "강의", "lecture", "#0f766e", School),
      icon("FileText", "학습자료", "material", "#334155", FileText),
      icon("ClipboardCheck", "과제 확인", "assignment", "#047857", ClipboardCheck),
      icon("Users", "멘토링", "mentoring", "#4338ca", Users),
      icon("MessageSquare", "Q&A", "qa", "#0f766e", MessageSquare),
      icon("Target", "목표", "goal", "#be123c", Target),
    ],
  },
  {
    title: "제작 / 운영",
    description: "장비, 운영, 제작, 팀 리드, 프로젝트 관리 태그 후보",
    accent: "#be123c",
    items: [
      icon("Boxes", "부품", "parts", "#92400e", Boxes),
      icon("PackageCheck", "장비 반납", "equipment_check", "#047857", PackageCheck),
      icon("Wrench", "정비", "maintenance", "#475569", Wrench),
      icon("Hammer", "제작", "fabrication", "#92400e", Hammer),
      icon("Pickaxe", "작업", "workshop", "#7c2d12", Pickaxe),
      icon("Rocket", "프로젝트 시작", "kickoff", "#db2777", Rocket),
      icon("Workflow", "프로세스", "process", "#0f766e", Workflow),
      icon("Settings", "운영 설정", "operations", "#334155", Settings),
      icon("ShieldCheck", "승인", "approval", "#166534", ShieldCheck),
      icon("Users", "팀", "team", "#4338ca", Users),
      icon("Crown", "대표", "lead", "#8a6d1c", Crown),
    ],
  },
];

export const TAG_ICON_OPTIONS = TAG_ICON_GROUPS.flatMap((group) => group.items);

export const TAG_ICON_COMPONENTS: Record<string, LucideIcon> = Object.fromEntries(
  TAG_ICON_OPTIONS.map((item) => [item.name, item.Icon]),
) as Record<string, LucideIcon>;

export function normalizeTagIconName(value: string | null | undefined) {
  const trimmed = value?.trim();
  if (!trimmed) return null;
  return TAG_ICON_COMPONENTS[trimmed] ? trimmed : null;
}

export function getTagIconComponent(value: string | null | undefined) {
  const name = normalizeTagIconName(value);
  return name ? TAG_ICON_COMPONENTS[name] : null;
}
